# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-11 20:18
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20180107_1052'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aboutme',
            name='phone',
        ),
        migrations.AddField(
            model_name='aboutme',
            name='age',
            field=models.IntegerField(default=24),
        ),
        migrations.AddField(
            model_name='aboutme',
            name='job_position',
            field=models.CharField(default='', max_length=250),
        ),
        migrations.AddField(
            model_name='aboutme',
            name='phone_number',
            field=models.CharField(default='', max_length=20, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'. Up to 13 digits allowed.", regex='^\\+?1?\\d{9,12}$')]),
        ),
    ]
