# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-11 21:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20180111_2018'),
    ]

    operations = [
        migrations.AddField(
            model_name='stat',
            name='category',
            field=models.CharField(choices=[('Professional Skills', 'Professional Skills'), ('Software Skills', 'Software Skills'), ('Additional Skills', 'Additional Skills'), ('Language Skills', 'Language Skills')], default='Professional Skills', max_length=100),
        ),
    ]
