# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-11 21:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_stat_category'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Stat',
            new_name='Skill',
        ),
    ]
