# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-12 17:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_auto_20180112_1710'),
    ]

    operations = [
        migrations.AddField(
            model_name='testimonial',
            name='image',
            field=models.ImageField(default='testimonial/default.png', upload_to='testimonial/'),
        ),
    ]
