# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-12 18:53
from __future__ import unicode_literals

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_testimonial_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='education',
            name='description',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='education',
            name='gpa_grade',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='workexperience',
            name='description',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
