# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-01-21 04:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_auto_20180112_1853'),
    ]

    operations = [
        migrations.AddField(
            model_name='education',
            name='left',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='workexperience',
            name='left',
            field=models.BooleanField(default=False),
        ),
    ]
