# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-18 19:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('description', models.TextField()),
                ('featured_image', models.ImageField(default='projects/images/default.jpg', upload_to='projects/images/')),
                ('date', models.DateField(verbose_name='Date')),
                ('ongoing', models.BooleanField(default=False)),
                ('enable', models.BooleanField(default=False)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField(unique=True)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='ProjectCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('slug', models.SlugField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProjectImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default='projects/images/default.jpg', upload_to='projects/images/')),
            ],
        ),
        migrations.AddField(
            model_name='project',
            name='associated_images',
            field=models.ManyToManyField(blank=True, to='project.ProjectImage'),
        ),
        migrations.AddField(
            model_name='project',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='project.ProjectCategory'),
        ),
    ]
